################################################################################
# phpmemcachedadmin - apenas redundancia do repo original
################################################################################

FROM processoeletronico/sei4-phpmemcachedadmin1.2.2:1.0.0