SHUTDOWN;
STARTUP MOUNT;
ALTER SYSTEM ENABLE RESTRICTED SESSION;
ALTER SYSTEM SET JOB_QUEUE_PROCESSES=0;
ALTER DATABASE OPEN;
ALTER DATABASE CHARACTER SET INTERNAL_USE WE8MSWIN1252;
ALTER DATABASE NATIONAL CHARACTER SET INTERNAL_USE AL16UTF16;
SHUTDOWN IMMEDIATE;
STARTUP;

CREATE TABLESPACE SEI DATAFILE '/u01/app/oracle/oradata/XE/sei.dbf' SIZE 50M AUTOEXTEND ON;
CREATE TABLESPACE SIP DATAFILE '/u01/app/oracle/oradata/XE/sip.dbf' SIZE 50M AUTOEXTEND ON;

ALTER USER SYSTEM IDENTIFIED BY P@ssword;
ALTER USER SYS IDENTIFIED BY P@ssword;

ALTER PROFILE DEFAULT LIMIT PASSWORD_VERIFY_FUNCTION NULL;
ALTER PROFILE DEFAULT limit PASSWORD_REUSE_TIME unlimited;
ALTER PROFILE DEFAULT limit PASSWORD_LIFE_TIME unlimited;

CREATE USER sei IDENTIFIED BY sei_user;
CREATE USER sip IDENTIFIED BY sip_user;

GRANT ALL PRIVILEGES TO sei;
GRANT ALL PRIVILEGES TO sip;

EXIT;
