<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'voku\\helper\\' => array($vendorDir . '/voku/anti-xss/src/voku/helper'),
    'voku\\' => array($vendorDir . '/voku/portable-utf8/src/voku'),
    'Tuupola\\' => array($vendorDir . '/tuupola/base32/src'),
    'Symfony\\Polyfill\\' => array($vendorDir . '/symfony/polyfill/src'),
    'Symfony\\Component\\Intl\\' => array($vendorDir . '/symfony/intl'),
    'Safe\\' => array($vendorDir . '/thecodingmachine/safe/lib', $vendorDir . '/thecodingmachine/safe/generated'),
    'ParagonIE\\ConstantTime\\' => array($vendorDir . '/paragonie/constant_time_encoding/src'),
    'OTPHP\\' => array($vendorDir . '/spomky-labs/otphp/src'),
    'Assert\\' => array($vendorDir . '/beberlei/assert/lib/Assert'),
);
