/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){function w(a){for(var d=0,p=0,n=0,q,c=a.$.rows.length;n<c;n++){q=a.$.rows[n];for(var l=d=0,b,e=q.cells.length;l<e;l++)b=q.cells[l],d+=b.colSpan;d>p&&(p=d)}return p}function t(a){return function(){var d=this.getValue(),d=!!(CKEDITOR.dialog.validate.integer().call(this,d)&&0<d);d||(alert(a),this.select());return d}}function r(a,d){var p=function(c){return new CKEDITOR.dom.element(c,a.document)},r=a.editable(),q=a.plugins.dialogadvtab;return{title:a.lang.table.title,minWidth:310,minHeight:CKEDITOR.env.ie?
310:280,getModel:function(c){return"tableProperties"!==this.dialog.getName()?null:(c=(c=c.getSelection())&&c.getRanges()[0])?c._getTableElement({table:1}):null},onLoad:function(){var c=this,a=c.getContentElement("advanced","advStyles");if(a)a.on("change",function(){var b=this.getStyle("width",""),a=c.getContentElement("info","txtWidth");a&&a.setValue(b,!0);b=this.getStyle("height","");(a=c.getContentElement("info","txtHeight"))&&a.setValue(b,!0)})},onShow:function(){var c=a.getSelection(),l=c.getRanges(),
b,e=this.getContentElement("info","txtRows"),g=this.getContentElement("info","txtCols"),u=this.getContentElement("info","txtWidth"),m=this.getContentElement("info","txtHeight");"tableProperties"==d&&((c=c.getSelectedElement())&&c.is("table")?b=c:0<l.length&&(CKEDITOR.env.webkit&&l[0].shrink(CKEDITOR.NODE_ELEMENT),b=a.elementPath(l[0].getCommonAncestor(!0)).contains("table",1)),this._.selectedElement=b);b?(this.setupContent(b),e&&e.disable(),g&&g.disable()):(e&&e.enable(),g&&g.enable());u&&u.onChange();
m&&m.onChange()},onOk:function(){var c=a.getSelection(),l=this._.selectedElement&&c.createBookmarks(),b=this._.selectedElement||p("table"),e={};this.commitContent(e,b);if(e.info){e=e.info;if(!this._.selectedElement)for(var g=b.append(p("tbody")),d=parseInt(e.txtRows,10)||0,m=parseInt(e.txtCols,10)||0,h=0;h<d;h++)for(var f=g.append(p("tr")),k=0;k<m;k++)f.append(p("td")).appendBogus();d=e.selHeaders;if(!b.$.tHead&&("row"==d||"both"==d)){f=b.getElementsByTag("thead").getItem(0);g=b.getElementsByTag("tbody").getItem(0);
m=g.getElementsByTag("tr").getItem(0);f||(f=new CKEDITOR.dom.element("thead"),f.insertBefore(g));for(h=0;h<m.getChildCount();h++)g=m.getChild(h),g.type!=CKEDITOR.NODE_ELEMENT||g.data("cke-bookmark")||(g.renameNode("th"),g.setAttribute("scope","col"));f.append(m.remove())}if(null!==b.$.tHead&&"row"!=d&&"both"!=d){f=new CKEDITOR.dom.element(b.$.tHead);for(g=b.getElementsByTag("tbody").getItem(0);0<f.getChildCount();){m=f.getFirst();for(h=0;h<m.getChildCount();h++)k=m.getChild(h),k.type!=CKEDITOR.NODE_ELEMENT||
d&&0===h?k.setAttribute("scope","row"):(k.renameNode("td"),k.removeAttribute("scope"));g.append(m,!0)}f.remove()}if(!this.hasColumnHeaders&&("col"==d||"both"==d))for(f=0;f<b.$.rows.length;f++)k=new CKEDITOR.dom.element(b.$.rows[f].cells[0]),k.renameNode("th"),"both"===d&&0===f?k.setAttribute("scope","col"):k.setAttribute("scope","row");if(this.hasColumnHeaders&&"col"!=d&&"both"!=d)for(h=0;h<b.$.rows.length;h++)f=new CKEDITOR.dom.element(b.$.rows[h]),"tbody"==f.getParent().getName()&&(k=new CKEDITOR.dom.element(f.$.cells[0]),
k.renameNode("td"),k.removeAttribute("scope"));e.txtHeight?b.setStyle("height",e.txtHeight):b.removeStyle("height");e.txtWidth?b.setStyle("width",e.txtWidth):b.removeStyle("width");b.getAttribute("style")||b.removeAttribute("style")}if(this._.selectedElement)try{c.selectBookmarks(l)}catch(n){}else a.insertElement(b),setTimeout(function(){var c=new CKEDITOR.dom.element(b.$.rows[0].cells[0]),l=a.createRange();l.moveToPosition(c,CKEDITOR.POSITION_AFTER_START);l.select()},0)},contents:[{id:"info",label:a.lang.table.title,
elements:[{type:"hbox",widths:[null,null],styles:["vertical-align:top"],children:[{type:"vbox",padding:0,children:[{type:"text",id:"txtRows","default":3,label:a.lang.table.rows,required:!0,controlStyle:"width:5em",validate:t(a.lang.table.invalidRows),setup:function(c){this.setValue(c.$.rows.length)},commit:n},{type:"text",id:"txtCols","default":2,label:a.lang.table.columns,required:!0,controlStyle:"width:5em",validate:t(a.lang.table.invalidCols),setup:function(c){this.setValue(w(c))},commit:n},{type:"html",
html:"\x26nbsp;"},{type:"select",id:"selHeaders",requiredContent:"th","default":"",label:a.lang.table.headers,items:[[a.lang.table.headersNone,""],[a.lang.table.headersRow,"row"],[a.lang.table.headersColumn,"col"],[a.lang.table.headersBoth,"both"]],setup:function(c){var a=this.getDialog();a.hasColumnHeaders=!0;for(var b=0;b<c.$.rows.length;b++){var e=c.$.rows[b].cells[0];if(e&&"th"!=e.nodeName.toLowerCase()){a.hasColumnHeaders=!1;break}}null!==c.$.tHead?this.setValue(a.hasColumnHeaders?"both":"row"):
this.setValue(a.hasColumnHeaders?"col":"")},commit:n},{type:"text",id:"txtBorder",requiredContent:"table[border]","default":a.filter.check("table[border]")?1:0,label:a.lang.table.border,controlStyle:"width:3em",validate:CKEDITOR.dialog.validate.number(a.lang.table.invalidBorder),setup:function(c){this.setValue(c.getAttribute("border")||"")},commit:function(c,a){this.getValue()?a.setAttribute("border",this.getValue()):a.removeAttribute("border")}},{id:"cmbAlign",type:"select",requiredContent:"table[align]",
"default":"center",label:a.lang.common.align,items:[[a.lang.common.notSet,""],[a.lang.common.left,"left"],[a.lang.common.center,"center"],[a.lang.common.right,"right"],["Recuo","recuo"]],setup:function(c){var a=c.getStyle("margin-right");c=c.getStyle("margin-left");var b="";"3pt"==a&&"auto"==c?b="right":"auto"==a&&"auto"==c?b="center":"auto"==a&&"3pt"==c?b="left":"auto"==a&&"1.18in"==c&&(b="recuo");this.setValue(b)},commit:function(a,d){var b=this.getDialog().getContentElement("advanced","advStyles");
if(this.getValue())switch(this.getValue()){case "left":b.updateStyle("margin-left","3pt");b.updateStyle("margin-right","auto");break;case "recuo":b.updateStyle("margin-left","1.18in");b.updateStyle("margin-right","auto");break;case "center":b.updateStyle("margin-left","auto");b.updateStyle("margin-right","auto");break;case "right":b.updateStyle("margin-left","auto"),b.updateStyle("margin-right","3pt")}else d.removeAttribute("align"),b.updateStyle("margin-left",""),b.updateStyle("margin-right","")}}]},
{type:"vbox",padding:0,children:[{type:"hbox",widths:["5em"],children:[{type:"text",id:"txtWidth",requiredContent:"table{width}",controlStyle:"width:5em",label:a.lang.common.width,title:a.lang.common.cssLengthTooltip,"default":a.filter.check("table{width}")?500>r.getSize("width")?"100%":500:0,getValue:v,validate:CKEDITOR.dialog.validate.cssLength(a.lang.common.invalidCssLength.replace("%1",a.lang.common.width)),onChange:function(){var a=this.getDialog().getContentElement("advanced","advStyles");a&&
a.updateStyle("width",this.getValue())},setup:function(a){a=a.getStyle("width");this.setValue(a)},commit:n}]},{type:"hbox",widths:["5em"],children:[{type:"text",id:"txtHeight",requiredContent:"table{height}",controlStyle:"width:5em",label:a.lang.common.height,title:a.lang.common.cssLengthTooltip,"default":"",getValue:v,validate:CKEDITOR.dialog.validate.cssLength(a.lang.common.invalidCssLength.replace("%1",a.lang.common.height)),onChange:function(){var a=this.getDialog().getContentElement("advanced",
"advStyles");a&&a.updateStyle("height",this.getValue())},setup:function(a){(a=a.getStyle("height"))&&this.setValue(a)},commit:n}]},{type:"html",html:"\x26nbsp;"},{type:"text",id:"txtCellSpace",requiredContent:"table[cellspacing]",controlStyle:"width:3em",label:a.lang.table.cellSpace,"default":"",validate:CKEDITOR.dialog.validate.number(a.lang.table.invalidCellSpacing),setup:function(a){this.setValue(a.getAttribute("cellSpacing")||"")},commit:function(a,d){var b=this.getDialog().getContentElement("advanced",
"advStyles");this.getValue()&&0!=this.getValue()?(d.setAttribute("cellSpacing",this.getValue()),b&&b.updateStyle("border-collapse","")):(d.removeAttribute("cellSpacing"),b&&b.updateStyle("border-collapse","collapse"))}},{type:"text",id:"txtCellPad",requiredContent:"table[cellpadding]",controlStyle:"width:3em",label:a.lang.table.cellPad,"default":"4",validate:CKEDITOR.dialog.validate.number(a.lang.table.invalidCellPadding),setup:function(a){this.setValue(a.getAttribute("cellPadding")||"")},commit:function(a,
d){this.getValue()?d.setAttribute("cellPadding",this.getValue()):d.removeAttribute("cellPadding")}}]}]},{type:"html",align:"right",html:""},{type:"vbox",padding:0,children:[{type:"text",id:"txtCaption",requiredContent:"caption",label:a.lang.table.caption,setup:function(a){this.enable();a=a.getElementsByTag("caption");if(0<a.count()){a=a.getItem(0);var d=a.getFirst(CKEDITOR.dom.walker.nodeType(CKEDITOR.NODE_ELEMENT));d&&!d.equals(a.getBogus())?(this.disable(),this.setValue(a.getText())):(a=CKEDITOR.tools.trim(a.getText()),
this.setValue(a))}},commit:function(c,d){if(this.isEnabled()){var b=this.getValue(),e=d.getElementsByTag("caption");if(b)0<e.count()?(e=e.getItem(0),e.setHtml("")):(e=new CKEDITOR.dom.element("caption",a.document),d.append(e,!0)),e.append(new CKEDITOR.dom.text(b,a.document));else if(0<e.count())for(b=e.count()-1;0<=b;b--)e.getItem(b).remove()}}}]}]},q&&q.createAdvancedTab(a,null,"table")]}}var v=CKEDITOR.tools.cssLength,n=function(a){var d=this.id;a.info||(a.info={});a.info[d]=this.getValue()};CKEDITOR.dialog.add("table",
function(a){return r(a,"table")});CKEDITOR.dialog.add("tableProperties",function(a){return r(a,"tableProperties")})})();