################################################################################
# Dockerfile de construção do container MailCatcher utilizado pelo SEI
# Apenas redundancia do repo oficial
################################################################################

FROM schickling/mailcatcher

############################# INÍCIO DA INSTALAÇÃO #############################
ENV TERM xterm

EXPOSE 1080