version: '2'
volumes:
    ${VOLUME_DB}:
        external: true
    ${VOLUME_ARQUIVOSEXTERNOS}:
        external: true
    ${VOLUME_CONTROLADOR_INSTALACAO}:
        external: true
    ${VOLUME_SOLR}:
        external: true
    ${VOLUME_CERTS}:
        external: true
    ${VOLUME_FONTES}:
        external: true
    ${VOLUME_OPENLDAP_SLAPD}:
        external: true
    ${VOLUME_OPENLDAP_DB}:
        external: true

services:
    storage-app:
        image: "busybox:latest"
        labels:
            io.rancher.container.start_once: "true"
        volumes:
            - ${VOLUME_ARQUIVOSEXTERNOS_MOUNT}:/sei/arquivos_externos_sei/:rw
            - ${VOLUME_FONTES_MOUNT}:/opt:rw
            - ${VOLUME_CONTROLADOR_INSTALACAO_MOUNT}:/sei/controlador-instalacoes
            - ${VOLUME_CERTS_MOUNT}:/sei/certs

    storage-certs:
        image: "busybox:latest"
        labels:
            io.rancher.container.start_once: "true"
        volumes:
            - ${VOLUME_CERTS_MOUNT}:/certs:rw
            
    storage-openldap:
        image: "busybox:latest"
        labels:
            io.rancher.container.start_once: "true"
        volumes:
            - ${VOLUME_OPENLDAP_SLAPD}:/etc/ldap/slapd.d
            - ${VOLUME_OPENLDAP_DB}:/var/lib/ldap
            
    #ldapadmin: #serviceldap
    #    image: ${DOCKER_IMAGE_OPENLDAP_PHPLDAPADMIN} #serviceldap
    #    environment: #serviceldap
    #        - PHPLDAPADMIN_LDAP_CLIENT_TLS=false #serviceldap
    #        - PHPLDAPADMIN_LDAP_HOSTS=openldap #serviceldap
    #        - PHPLDAPADMIN_HTTPS=false #serviceldap
    #        - PHPLDAPADMIN_TRUST_PROXY_SSL=true #serviceldap
    #        - VIRTUAL_HOST=http://${APP_HOST}/phpldapadmin*,https://${APP_HOST}/phpldapadmin* #serviceldap
    #        - EXCLUDE_PORTS=443 #serviceldap
    #        - FORCE_SSL=true #serviceldap
    #    links: #serviceldap
    #        - openldap:openldap #serviceldap
    #openldap: #serviceldap
    #    image: processoeletronico/sei4-osixialdap1.2.2:1.0.0 #serviceldap
    #    environment: #serviceldap
    #        - KEEP_EXISTING_CONFIG=false #serviceldap
    #        - LDAP_ADMIN_PASSWORD=${OPENLDAP_ADMIN_PASSWORD} #serviceldap
    #        - LDAP_BACKEND=mdb #serviceldap
    #        - LDAP_BASE_DN= #serviceldap
    #        - LDAP_CONFIG_PASSWORD=configldap #serviceldap
    #        - LDAP_DOMAIN=pen.gov.br #serviceldap
    #        - LDAP_LOG_LEVEL=256 #serviceldap
    #        - LDAP_ORGANISATION=Processo Eletronico Nacional #serviceldap
    #        - LDAP_READONLY_USER=false #serviceldap
    #        - LDAP_REMOVE_CONFIG_AFTER_SETUP=true #serviceldap
    #        - LDAP_REPLICATION=false #serviceldap
    #        - LDAP_RFC2307BIS_SCHEMA=false #serviceldap
    #        - LDAP_SSL_HELPER_PREFIX=ldap #serviceldap
    #        - LDAP_TLS=false #serviceldap
    #    volumes_from: #serviceldap
    #        - storage-openldap #serviceldap
                
    #jod: #servicejod
    #    image: ${DOCKER_IMAGE_JOD} #servicejod
    
    #mail: #servicemail
    #    image: ${DOCKER_IMAGE_MAIL} #servicemail
    #    command: ["mailcatcher", "--no-quit", "--foreground", "--ip=0.0.0.0", "--smtp-port=25", "--http-port=80"] #servicemail
    #    expose: #servicemail
    #        - 25 #servicemail
    #        - 80 #servicemail
    #    environment: #servicemail
    #        - VIRTUAL_HOST=http://${APP_HOST}/mailadmin*,https://${APP_HOST}/mailadmin*,http://${APP_HOST}/assets*,https://${APP_HOST}/assets*,http://${APP_HOST}/messages*,https://${APP_HOST}/messages* #servicemail
    #        - FORCE_SSL=true #servicemail
    #        - EXCLUDE_PORTS=25,1080,1025 #servicemail
    #        - EXTRA_SETTINGS=http-request set-path "%[path\,regsub(^/mailadmin\,/)]" #servicemail
    
    memcached:
        image: ${DOCKER_IMAGE_MEMCACHED}
    
    #memcachedadmin: #servicememcachedadmin
    #    image: ${DOCKER_IMAGE_MEMCACHEDADMIN} #servicememcachedadmin
    #    environment: #servicememcachedadmin
    #        - VIRTUAL_HOST=http://${APP_HOST}/memcachedadmin*,https://${APP_HOST}/memcachedadmin* #servicememcachedadmin
    #        - FORCE_SSL=true #servicememcachedadmin

    db:
        image: ${DOCKER_IMAGE_BD}
        labels:
            io.rancher.container.pull_image: always
            io.rancher.sidekicks: storage-db
        volumes:
            - ${VOLUME_DB}:${DB_DATA_DIRECTORY}
    
    #dbadmin: #servicedbadmin
    #    image: ${DOCKER_IMAGE_DBADMIN} #servicedbadmin
    #    environment: #servicedbadmin
    #        - VIRTUAL_HOST=http://${APP_HOST}/dbadmin*,https://${APP_HOST}/dbadmin* #servicedbadmin
    #        - FORCE_SSL=true #servicedbadmin
            
  
    solr:
        image: ${DOCKER_IMAGE_SOLR}
        environment:
            - VIRTUAL_HOST=http://${APP_HOST}/solr*,https://${APP_HOST}/solr*
            - FORCE_SSL=true
        volumes:
            - ${VOLUME_SOLR}:${SOLR_DATA_DIRECTORY}
        
    
    app-atualizador:
        image: ${DOCKER_IMAGE_APP}
        entrypoint: "/entrypoint-atualizador.sh"
        volumes_from:
            - storage-app
            - storage-certs
        volumes:
            - /sei/controlador-instalacoes
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.start_once: 'true'
        environment:
        - APP_PROTOCOLO=${APP_PROTOCOLO}
        - APP_HOST=${APP_HOST}
        - APP_ORGAO=${APP_ORGAO}
        - APP_ORGAO_DESCRICAO=${APP_ORGAO_DESCRICAO}
        - APP_NOMECOMPLEMENTO=${APP_NOMECOMPLEMENTO}
        - APP_MEMCACHED_HOST=${APP_MEMCACHED_HOST}
        - APP_DB_TIPO=${APP_DB_TIPO}
        - APP_DB_HOST=${APP_DB_HOST}
        - APP_DB_PORTA=${APP_DB_PORTA}
        - APP_DB_SIP_BASE=${APP_DB_SIP_BASE}
        - APP_DB_SIP_USERNAME=${APP_DB_SIP_USERNAME}
        - APP_DB_SIP_PASSWORD=${APP_DB_SIP_PASSWORD}
        - APP_DB_SEI_BASE=${APP_DB_SEI_BASE}
        - APP_DB_SEI_USERNAME=${APP_DB_SEI_USERNAME}
        - APP_DB_SEI_PASSWORD=${APP_DB_SEI_PASSWORD}
        - APP_DB_ROOT_USERNAME=${APP_DB_ROOT_USERNAME}
        - APP_DB_ROOT_PASSWORD=${APP_DB_ROOT_PASSWORD}
        - APP_SIP_CHAVE_ACESSO=${APP_SIP_CHAVE_ACESSO}
        - APP_SEI_CHAVE_ACESSO=${APP_SEI_CHAVE_ACESSO}
        - APP_SOLR_URL=${APP_SOLR_URL}
        - APP_SOLR_CORE_PROTOCOLOS=${APP_SOLR_CORE_PROTOCOLOS}
        - APP_SOLR_TEMPO_COMMIT_PROTOCOLOS=${APP_SOLR_TEMPO_COMMIT_PROTOCOLOS}
        - APP_SOLR_CORE_BASECONHECIMENTO=${APP_SOLR_CORE_BASECONHECIMENTO}
        - APP_SOLR_TEMPO_COMMIT_BASECONHECIMENTO=${APP_SOLR_TEMPO_COMMIT_BASECONHECIMENTO}
        - APP_SOLR_CORE_PUBLICACOES=${APP_SOLR_CORE_PUBLICACOES}
        - APP_SOLR_TEMPO_COMMIT_PUBLICACOES=${APP_SOLR_TEMPO_COMMIT_PUBLICACOES}
        - APP_MAIL_TIPO=${APP_MAIL_TIPO}
        - APP_MAIL_SERVIDOR=${APP_MAIL_SERVIDOR}
        - APP_MAIL_PORTA=${APP_MAIL_PORTA}
        - APP_MAIL_CODIFICACAO=${APP_MAIL_CODIFICACAO}
        - APP_MAIL_MAXDESTINATARIOS=${APP_MAIL_MAXDESTINATARIOS}
        - APP_MAIL_MAXTAMANHOANEXOSMB=${APP_MAIL_MAXTAMANHOANEXOSMB}
        - APP_MAIL_SEGURANCA=${APP_MAIL_SEGURANCA}
        - APP_MAIL_AUTENTICAR=${APP_MAIL_AUTENTICAR}
        - APP_MAIL_USUARIO=${APP_MAIL_USUARIO}
        - APP_MAIL_SENHA=${APP_MAIL_SENHA}
        - APP_MAIL_PROTEGIDO=${APP_MAIL_PROTEGIDO}
        - OPENLDAP_PRESENTE=${OPENLDAP_PRESENTE}
        - OPENLDAP_ADMIN_PASSWORD=${OPENLDAP_ADMIN_PASSWORD}
        - OPENLDAP_DESLIGAR_NO_ORGAO_0=${OPENLDAP_DESLIGAR_NO_ORGAO_0}
        - MODULO_ESTATISTICAS_INSTALAR=${MODULO_ESTATISTICAS_INSTALAR}
        - MODULO_ESTATISTICAS_VERSAO=${MODULO_ESTATISTICAS_VERSAO}
        - MODULO_ESTATISTICAS_URL=${MODULO_ESTATISTICAS_URL}
        - MODULO_ESTATISTICAS_SIGLA=${MODULO_ESTATISTICAS_SIGLA}
        - MODULO_ESTATISTICAS_CHAVE=${MODULO_ESTATISTICAS_CHAVE}
        - MODULO_WSSEI_INSTALAR=${MODULO_WSSEI_INSTALAR}
        - MODULO_WSSEI_VERSAO=${MODULO_WSSEI_VERSAO}
        - MODULO_WSSEI_URL_NOTIFICACAO=${MODULO_WSSEI_URL_NOTIFICACAO}
        - MODULO_WSSEI_ID_APP=${MODULO_WSSEI_ID_APP}
        - MODULO_WSSEI_CHAVE=${MODULO_WSSEI_CHAVE}
        - MODULO_PEN_INSTALAR=${MODULO_PEN_INSTALAR}
        - MODULO_PEN_VERSAO=${MODULO_PEN_VERSAO}
        - MODULO_PEN_CERTIFICADO=${MODULO_PEN_CERTIFICADO}
        - MODULO_PEN_CERTIFICADO_SENHA=${MODULO_PEN_CERTIFICADO_SENHA}
        - MODULO_PEN_WEBSERVICE=${MODULO_PEN_WEBSERVICE}
        links:
        - db:db
        - memcached:memcached
        - solr:solr #servicesolr
        #- jod:jod #servicejod
        #- openldap:openldap #serviceldap
    app:
        image: ${DOCKER_IMAGE_APP}
        entrypoint: "/entrypoint.sh"
        #ports:
        #    - ${APP_PORTA_80_MAP}
        #    - ${APP_PORTA_443_MAP}
        volumes_from:
            - storage-app
            - storage-certs
        labels:
            io.rancher.container.pull_image: always
            io.rancher.sidekicks: storage-arquivosexternos,storage-fontes,app-atualizador    
        environment:
        - APP_PROTOCOLO=${APP_PROTOCOLO}
        - APP_HOST=${APP_HOST}
        - APP_ORGAO=${APP_ORGAO}
        - APP_ORGAO_DESCRICAO=${APP_ORGAO_DESCRICAO}
        - APP_NOMECOMPLEMENTO=${APP_NOMECOMPLEMENTO}
        - APP_MEMCACHED_HOST=${APP_MEMCACHED_HOST}
        - APP_DB_TIPO=${APP_DB_TIPO}
        - APP_DB_HOST=${APP_DB_HOST}
        - APP_DB_PORTA=${APP_DB_PORTA}
        - APP_DB_SIP_BASE=${APP_DB_SIP_BASE}
        - APP_DB_SIP_USERNAME=${APP_DB_SIP_USERNAME}
        - APP_DB_SIP_PASSWORD=${APP_DB_SIP_PASSWORD}
        - APP_DB_SEI_BASE=${APP_DB_SEI_BASE}
        - APP_DB_SEI_USERNAME=${APP_DB_SEI_USERNAME}
        - APP_DB_SEI_PASSWORD=${APP_DB_SEI_PASSWORD}
        - APP_DB_ROOT_USERNAME=${APP_DB_ROOT_USERNAME}
        - APP_DB_ROOT_PASSWORD=${APP_DB_ROOT_PASSWORD}
        - APP_SIP_CHAVE_ACESSO=${APP_SIP_CHAVE_ACESSO}
        - APP_SEI_CHAVE_ACESSO=${APP_SEI_CHAVE_ACESSO}
        - APP_SOLR_URL=${APP_SOLR_URL}
        - APP_SOLR_CORE_PROTOCOLOS=${APP_SOLR_CORE_PROTOCOLOS}
        - APP_SOLR_TEMPO_COMMIT_PROTOCOLOS=${APP_SOLR_TEMPO_COMMIT_PROTOCOLOS}
        - APP_SOLR_CORE_BASECONHECIMENTO=${APP_SOLR_CORE_BASECONHECIMENTO}
        - APP_SOLR_TEMPO_COMMIT_BASECONHECIMENTO=${APP_SOLR_TEMPO_COMMIT_BASECONHECIMENTO}
        - APP_SOLR_CORE_PUBLICACOES=${APP_SOLR_CORE_PUBLICACOES}
        - APP_SOLR_TEMPO_COMMIT_PUBLICACOES=${APP_SOLR_TEMPO_COMMIT_PUBLICACOES}
        - APP_MAIL_TIPO=${APP_MAIL_TIPO}
        - APP_MAIL_SERVIDOR=${APP_MAIL_SERVIDOR}
        - APP_MAIL_PORTA=${APP_MAIL_PORTA}
        - APP_MAIL_CODIFICACAO=${APP_MAIL_CODIFICACAO}
        - APP_MAIL_MAXDESTINATARIOS=${APP_MAIL_MAXDESTINATARIOS}
        - APP_MAIL_MAXTAMANHOANEXOSMB=${APP_MAIL_MAXTAMANHOANEXOSMB}
        - APP_MAIL_SEGURANCA=${APP_MAIL_SEGURANCA}
        - APP_MAIL_AUTENTICAR=${APP_MAIL_AUTENTICAR}
        - APP_MAIL_USUARIO=${APP_MAIL_USUARIO}
        - APP_MAIL_SENHA=${APP_MAIL_SENHA}
        - APP_MAIL_PROTEGIDO=${APP_MAIL_PROTEGIDO}
        - OPENLDAP_PRESENTE=${OPENLDAP_PRESENTE}
        - MODULO_ESTATISTICAS_INSTALAR=${MODULO_ESTATISTICAS_INSTALAR}
        - MODULO_ESTATISTICAS_VERSAO=${MODULO_ESTATISTICAS_VERSAO}
        - MODULO_ESTATISTICAS_URL=${MODULO_ESTATISTICAS_URL}
        - MODULO_ESTATISTICAS_SIGLA=${MODULO_ESTATISTICAS_SIGLA}
        - MODULO_ESTATISTICAS_CHAVE=${MODULO_ESTATISTICAS_CHAVE}
        - MODULO_WSSEI_INSTALAR=${MODULO_WSSEI_INSTALAR}
        - MODULO_WSSEI_VERSAO=${MODULO_WSSEI_VERSAO}
        - MODULO_WSSEI_URL_NOTIFICACAO=${MODULO_WSSEI_URL_NOTIFICACAO}
        - MODULO_WSSEI_ID_APP=${MODULO_WSSEI_ID_APP}
        - MODULO_WSSEI_CHAVE=${MODULO_WSSEI_CHAVE}
        - VIRTUAL_HOST=https://${APP_HOST}/sei*,https://${APP_HOST}/sip*,https://${APP_HOST}/infra*,http://${APP_HOST}/sei*,http://${APP_HOST}/sip*,http://${APP_HOST}/infra*
        #- EXCLUDE_PORTS=443
        #- EXCLUDE_PORTS=80
        #- EXTRA_ROUTE_SETTINGS=ssl verify none
        - COOKIE=SRV insert indirect nocache
        - MODULO_PEN_INSTALAR=${MODULO_PEN_INSTALAR}
        - MODULO_PEN_VERSAO=${MODULO_PEN_VERSAO}
        - MODULO_PEN_CERTIFICADO=${MODULO_PEN_CERTIFICADO}
        - MODULO_PEN_CERTIFICADO_SENHA=${MODULO_PEN_CERTIFICADO_SENHA}
        - MODULO_PEN_WEBSERVICE=${MODULO_PEN_WEBSERVICE}
        links:
        - db:db
        - memcached:memcached
        - solr:solr #servicesolr
        #- jod:jod #servicejod
        #- openldap:openldap #serviceldap
    #balanceador: #servicebal
    #    image: ${DOCKER_IMAGE_BALANCEADOR} #servicebal
    #    links: #servicebal
    #        - app #servicebal
    #        - solr #servicesolr #servicebal
    #        - mail #servicemail #servicebal
    #        - ldapadmin #serviceldap #servicebal
    #        - memcachedadmin #servicememcachedadmin #servicebal
    #        - dbadmin #servicedbadmin #servicebal
    #    environment: #servicebal
    #        - EXTRA_FRONTEND_SETTINGS_80=use_backend stats if { path_beg -i /haproxy }, acl is_root path -i /, redirect code 301 location http://${APP_HOST}/sei/ if is_root #servicebal
    #        - EXTRA_FRONTEND_SETTINGS_443=use_backend stats if { path_beg -i /haproxy }, acl is_root path -i /, redirect code 301 location http://${APP_HOST}/sei/ if is_root #servicebal
    #        - CERT_FOLDER=/certs #servicebal
    #    volumes_from: #servicebal
    #        - storage-certs #servicebal
    #    volumes: #servicebal
    #        - /var/run/docker.sock:/var/run/docker.sock #servicebal
    #    ports: #servicebal
    #        - ${BALANCEADOR_PORTA_80_MAP} #servicebal
    #        - ${BALANCEADOR_PORTA_443_MAP} #servicebal