################################################################################
# SqlServer Imagem Alternativa - apenas redundancia do repo oficial
################################################################################

FROM processoeletronico/sei4-sqlserver:1.0
#liaisonintl/mssql-server-linux