################################################################################
# Oracle Imagem Alternativa - apenas redundancia do repo oficial
################################################################################

FROM oracleinanutshell/oracle-xe-11g