################################################################################
# Oracle Imagem Alternativa - apenas redundancia do repo oficial
################################################################################

#FROM oracleinanutshell/oracle-xe-11g:latest
FROM container-registry.oracle.com/database/express:21.3.0-xe